### PR TITLE
refactor: top section budget details #P23-357 

### PR DESCRIPTION
**Pull request by wyola**
## Layout of the top section of the budget's details page
task: https://tracker.intive.com/jira/browse/PATRO23-357

Let me know what you think about the layout of the top part, try resizing the page down to 375px.

It is best if you test it by logging in with the same credentials as for "People in budget":
https://intive-apu8934.slack.com/archives/C04R6LM4JSV/p1684873435505349?thread_ts=1684873404.585919&cid=C04R6LM4JSV

Task is related to this part:

image

### Notes:
- it has to look good both for short and long budget names/descriptions, so there is no satisfying every possibility 

### What changed:
- extra icon for adding the budget to favorite
- icons move to dropdown menu on smaller screens
- layout HTML structure, because of the "people in budget task"
- suspense was updated accordingly
- small refactor of the `Favourite` component - when a different budget was loaded using side nav menu the value of isFavourite was not updating, hence:

```
  useEffect(() => {
    setIsFavourite(isFav);
  }, [budgetId, isFav]);
```
- I changed `TransactionDropdownMenu` to have more generic name `DropdownMenu`, since it is now used not only in `TransactionsTable` but also in budget's details page mobile view

### CODE REVIEW

**Review by Alessiass — APPROVED** [review]

**Review by Noshi96 — COMMENTED** [review]
Looks great! I have noticed that the tooltip doesn't open on mobile. What do you think, is there a way to make it open when clicked? If so, we could also apply this to long budget titles that we can't check on mobile until we get to the edit modal.

**Review by zuzannapaw — APPROVED** [review]
I agree with @Noshi96 idea, however it looks superb ✨ Good job

**Comment by wyola** [comment]
> Looks great! I have noticed that the tooltip doesn't open on mobile. What do you think, is there a way to make it open when clicked? If so, we could also apply this to long budget titles that we can't check on mobile until we get to the edit modal.

@Noshi96 I semi-agree 😅 there probably should be some functionality for it on mobile, but tooltips are not displayed on mobiles. Then it would have to be maybe something else, like a `Popover`, then the `Avatar` should be a button, then maybe it should lead to user's account's details, which we don't have etc etc... We would be starting an avalanche here. Also, radix's tooltip does not really have an option to add this functionality, and the `people in budget` task was about hovering, and this task is about the layout.

**Comment by Noshi96** [comment]
> @Noshi96 I semi-agree 😅 there probably should be some functionality for it on mobile, but tooltips are not displayed on mobiles. Then it would have to be maybe something else, like a `Popover`, then the `Avatar` should be a button, then maybe it should lead to user's account's details, which we don't have etc etc... We would be starting an avalanche here. Also, radix's tooltip does not really have an option to add this functionality, and the `people in budget` task was about hovering, and this task is about the layout.

@wyola it's ok, we don't want an avalanche 😅  I thought there might be an easy way to apply this functionality. And you're right that it's beyond the scope of people on a budget task.

**Review by PawelPazderski — APPROVED** [review]
Looks and works really nice 🚀 Maybe we could make the budget icon even smaller at mobile view and give more space for information, but I believe this will look better when the side nav stops stealing the space. One small issue I ran into while changing the window size while dropdown open:

image

Other than that, good job.

**Comment by wyola** [comment]
> Looks and works really nice 🚀 Maybe we could make the budget icon even smaller at mobile view and give more space for information, but I believe this will look better when the side nav stops stealing the space. One small issue I ran into while changing the window size while dropdown open:
> 
> image
> 
> Other than that, good job.

thanks, I fixed it 🔨 nice drawings btw 😄

**Review by Noshi96 — APPROVED** [review]
Oh, I discovered that on mobile, when I touch and hold a specific avatar, the alternate text of that avatar is displayed, which solves my question about which avatar belongs to the user. Other than that, great job! ✨

**Review by Vectari — APPROVED** [review]

**Review by monika-klokosinska-intive — APPROVED** [review]

**Pull request merged**
