### PR TITLE
fix: removed default color for icon #P23-119

### PR DESCRIPTION
**Pull request by Alessiass**
Removed default color for icon from black to inherit it from parent element

### CODE REVIEW

**Review by wlechowicz — APPROVED** [review]

**Review by PawelPazderski — APPROVED** [review]
Looks fine to me.

**Review by AzulloCyll — APPROVED** [review]

**Review by bdeluga — APPROVED** [review]
Good change.

**Review by Noshi96 — APPROVED** [review]

**Review by wyola — APPROVED** [review]
Good change

**Review by zuzannapaw — APPROVED** [review]

**Review by Vectari — APPROVED** [review]

**Review by aniasgit — APPROVED** [review]
Looks good to me :)

**Pull request merged**
