### PR TITLE
fix: remove budgets fixes - cache clear and modal colors #P23-42

### PR DESCRIPTION
**Pull request by Alessiass**
## Fixes 🔧

- Budgets list is now refreshing after successful budget creation
- Prevents conflicts after removed budgets
- Querykeys dupe cleanup
- Confirm toast color fix

### Update:

- Added harl to statistics endpoint 🦺

### CODE REVIEW

**Review by wyola — COMMENTED** [review]
It would be good to refres budget list faster after removing the budget. Right now it takes some time and you can click on removed budget.


https://github.com/intive/patronage2023-js/assets/80450315/53b5b00b-43ee-4fcc-951c-9900ab98b9df

**Comment by Alessiass** [comment]
> It would be good to refres budget list faster after removing the budget. Right now it takes some time and you can click on removed budget.
> 
>  remove.1.mp4

Good find! I'll try to find solution for it tomorrow.

**Comment by Vectari** [comment]
During my tests removed budget disappear from list immediately, but it's hard to review with this all BE errors. I'll back tomorrow

**Review by Vectari — COMMENTED** [review]
During my tests removed budget disappear from list immediately, but it's hard to review with this all BE errors. I'll back tomorrow

**Review by zuzannapaw — COMMENTED** [review]
I had the situation that @Vectari described. I would be happy to come back to this pr when it will be free from these errors.

**Review by monika-klokosinska-intive — COMMENTED** [review]
@Alessiass LGTM, but as other mentioned it would be better if we could test it freely on vercel.

**Review by monika-klokosinska-intive — APPROVED** [review]

**Pull request merged**
